name = "gleave"
version = "1.0.1"

description = "Exit your Gleam CLI program with a status code"
licenses = ["WTFPL"]
repository = { type = "github", user = "ollien", repo = "gleave" }

[dev-dependencies]
